BUG: Remove override keyword.
InsightSoftwareConsortium/ITKVariationalRegistration pull request #25
Opened 2018-10-13 14:50 UTC by jhlegarreta

Remove the `override` keyword from the
`itk::VariationalRegistrationFilter::InitializeIteration` method: the base
class `itk::DenseFiniteDifferenceImageFilter` does not have such a method,
and thus it cannot be overriden.

Fixes Doxygen warnings raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=5578653

2018-10-13 15:31 UTC, jhlegarreta commented
I find it weird that it's Doxygen that reports this and not the compilation...

For the rest of Doxygen failures reported in the link, I do not see where they come from; I've revised the inheritance and they seem to be OK, but would be happy to fix them if someone is able to spot the issues.

2018-10-17 15:13 UTC, thewtex requested changes
This keyword looks to be desirable -- `itk::VariationalRegistrationFilter` also inherits from `itk::FiniteDifferenceImageFilter`, but it also has the function:

https://itk.org/Doxygen/html/classitk_1_1FiniteDifferenceImageFilter.html#a2ca930cafa0bd5651661a8786655ad0c

The CDash warning I see points to a different class, but its base class also has a virtual `InitializeIteration`.

It looks like the Doxygen build is not expanding some ITK preprocessor macros, although we define them in the ITK Doxygen configuration...

2018-10-18 20:08 UTC, jhlegarreta commented
@thewtex true :grimacing:

> It looks like the Doxygen build is not expanding some ITK preprocessor macros, although we define them in the ITK Doxygen configuration...

Just guessing: may be the empty implementations are skipped?

2018-10-25 17:23 UTC, dzenanz commented
Can this PR be closed?

2018-10-25 17:34 UTC, jhlegarreta commented
After having read Matt's comment and having looked further into the issue, I guess we can.

2018-10-25 17:35 UTC, closed without merging